version: "3"

networks:
  tt_net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - tt_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - tt_net

  influxdb:
    image: influxdb:alpine
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      - tt_net
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - 8888:8888
    networks: 
      - tt_net
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    links:
      - influxdb

  # kapacitor:
  #   image: kapacitor
  #   environment:
  #     KAPACITOR_HOSTNAME: kapacitor
  #     KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
  #   links:
  #     - influxdb
  #   ports:
  #     - 9092:9092

  # telegraf:
  #   image: telegraf
  #   volumes:
  #     - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #   links:
  #     - influxdb
  #   ports:
  #     - 8092:8092/udp
  #     - 8094:8094
  #     - 8125:8125/udp